name: Subtree Sync

on:
  push:
    branches:
      - main

jobs:
  sync-to-constants:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_TOKEN }} # PAT 사용

      - name: Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add remote & push
        run: |
          git remote add constants-repo https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/Altsoft-KimDongYoung/0131_constants.git
          git subtree push --prefix=constants-test constants-repo main
